# Generated by Django 3.0.7 on 2020-11-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_fill_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработанный'), ('processed', 'Обработанный')], default='unprocessed', max_length=20),
        ),
    ]
