# Generated by Django 3.0.7 on 2020-11-13 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 11, 3, 3, 967495, tzinfo=utc)),
        ),
    ]
