# Generated by Django 3.0.7 on 2020-11-13 11:15

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_called_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
