# Generated by Django 3.0.7 on 2021-01-27 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
        ('foodcartapp', '0045_order_payment_method'),
    ]

    operations = [
    ]
